### ISSUE TITLE
aggregate inside a docker

### ISSUE THREAD

**Issue by foutoucour** [acsone/git-aggregator#17]
Hello guys,

I am new to git-aggregator and I have some issues that I can't explain:
* Merges seem to be required. Is that by design? I would like to use the module to pull some repo without applying any merges/updates on it.
* I have a difference between the behavior on the host and inside my docker.
My docker is pretty simple,  based on odoo:10.0. 

Here is the traceback from inside the docker
```Step 21/22 : COPY ./repos.yaml /tmp
 ---> d48a929fb012
Step 22/22 : RUN cd /tmp     && gitaggregate -c /tmp/repos.yaml     && mv -f /tmp/third/*/* ${THIRD_PARTY_ADDONS}     && rm /tmp/third
 ---> Running in 31ad195be6a9
(INFO) [18:02:29] git_aggregator.repo  Start aggregation of /tmp/third/l10n-canada
(INFO) [18:02:29] git_aggregator.repo  Init empty git repository in /tmp/third/l10n-canada
Initialized empty Git repository in /tmp/third/l10n-canada/.git/
(INFO) [18:02:29] git_aggregator.repo  Switch to branch 9c1b75a837c0f15e127ee656e871b78db1407505
Switched to a new branch '9c1b75a837c0f15e127ee656e871b78db1407505'
(INFO) [18:02:29] git_aggregator.repo  Adding remote oca <https://github.com/OCA/l10n-canada>
(INFO) [18:02:29] git_aggregator.repo  Adding remote sfl <https://github.com/savoirfairelinux/l10n-canada>
(INFO) [18:02:29] git_aggregator.repo  Fetching required remotes
error: no such remote ref 40176efdbd2acbd4ae70e548af4a077afed11d5d
Traceback (most recent call last):
  File "/usr/local/bin/gitaggregate", line 11, in <module>
    load_entry_point('git-aggregator==1.2.1.dev6+g36a77e5', 'console_scripts', 'gitaggregate')()
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/main.py", line 131, in main
    run(args)
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/main.py", line 174, in run
    r.aggregate()
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/repo.py", line 179, in aggregate
    self.fetch()
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/repo.py", line 202, in fetch
    self.log_call(cmd, cwd=self.cwd)
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/repo.py", line 156, in log_call
    ret = callwith(cmd, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(u'git', u'fetch', 'sfl', '40176efdbd2acbd4ae70e548af4a077afed11d5d')' returned non-zero exit status 128
ERROR: Service 'odoo' failed to build: The command '/bin/sh -c cd /tmp     && gitaggregate -c /tmp/repos.yaml     && mv -f /tmp/third/*/* ${THIRD_PARTY_ADDONS}     && rm /tmp/third' returned a non-zero code: 1
```

While it works smoothly on the host:
```
(gitaggregate) ftc@ftc-XPS-13-9360 ~/p/odoo-aggr> gitaggregate -c ./repos.yaml 
(INFO) [13:02:58] git_aggregator.repo  Start aggregation of /home/ftc/projects/odoo-aggr/third/l10n-canada
(INFO) [13:02:58] git_aggregator.repo  Init empty git repository in /home/ftc/projects/odoo-aggr/third/l10n-canada
Initialized empty Git repository in /home/ftc/projects/odoo-aggr/third/l10n-canada/.git/
(INFO) [13:02:58] git_aggregator.repo  Switch to branch 9c1b75a837c0f15e127ee656e871b78db1407505
Switched to a new branch '9c1b75a837c0f15e127ee656e871b78db1407505'
(INFO) [13:02:58] git_aggregator.repo  Adding remote oca <https://github.com/OCA/l10n-canada>
(INFO) [13:02:58] git_aggregator.repo  Adding remote sfl <https://github.com/savoirfairelinux/l10n-canada>
(INFO) [13:02:58] git_aggregator.repo  Fetching required remotes
remote: Counting objects: 1280, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1280 (delta 1), reused 0 (delta 0), pack-reused 1278
Receiving objects: 100% (1280/1280), 392.40 KiB | 749.00 KiB/s, done.
Resolving deltas: 100% (834/834), done.
From https://github.com/savoirfairelinux/l10n-canada
 * branch            40176efdbd2acbd4ae70e548af4a077afed11d5d -> FETCH_HEAD
(INFO) [13:02:59] git_aggregator.repo  Pull sfl, 40176efdbd2acbd4ae70e548af4a077afed11d5d
(INFO) [13:02:00] git_aggregator.repo  Execute shell after commands
(INFO) [13:02:00] git_aggregator.repo  End aggregation of /home/ftc/projects/odoo-aggr/third/l10n-canada
```
repos.yaml:
```./third/l10n-canada:
  remotes:
    oca: https://github.com/OCA/l10n-canada
    sfl: https://github.com/savoirfairelinux/l10n-canada
  merges:
    - sfl 40176efdbd2acbd4ae70e548af4a077afed11d5d
  target: oca 9c1b75a837c0f15e127ee656e871b78db1407505
```

Do you see anything that should be changed?

**Comment by foutoucour** [comment]
Error 18 ;)
My local gitconfig is different... doh

**Comment by sorvis** [comment]
@foutoucour  Just wondering what was the local gitconfig that ended up being the cause if you happen to recall that far back / happen to have it documented in a dockerfile?

**Comment by pleirb** [comment]
I have the same problem. I am using Ubuntu 24.04 with virtual env configured for python 3
git 2.43.0
git-aggregator 2.1.0
Some time has passed, is it that in my case I should downgrade the git version?
