### ISSUE TITLE
[Question] How to use an env variable for pr number?

### ISSUE THREAD

**Issue by obayit** [acsone/git-aggregator#49]
I have this repo in the config file:
```
./odoo-staging:
  defaults:
    depth: $DEPTH_MERGE
  remotes:
    main: git@github.com:obayit/project.git
  target: main project
  merges:
    - main project
    - main refs/pull/$TEST_PR/head
```
When I run gitaggregate, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/gitaggregate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/main.py", line 176, in main
    run(args)
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/main.py", line 237, in run
    args.config, args.expand_env, args.env_file, args.force)
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/config.py", line 159, in load_config
    config = config.substitute(environment)
  File "/usr/local/lib/python3.5/string.py", line 129, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/local/lib/python3.5/string.py", line 119, in convert
    val = mapping[named]
KeyError: 'TEST_PR'

```

**Comment by obayit** [comment]
Wait. It works just fine. The problem must be somewhere else.
